# Generated by Django 3.1.7 on 2021-03-24 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210324_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', related_query_name='posts', to='blog.category'),
        ),
    ]
