# Generated by Django 3.1.7 on 2021-04-13 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210324_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 2, 34, 33, 541897, tzinfo=utc)),
        ),
    ]
